### ISSUE TITLE
How to get token when already connected

### ISSUE THREAD

**Issue by qdm12** [pia-foss/manual-connections#10]
Hi there,

My situation is quite simple: I am connected with Openvpn to a PIA server. I also have the VPN gateway IP address available.

Is there a way to obtain a token using my username and password from the VPN gateway IP address or from an API endpoint directly? I tried to `curl --request POST --data '{"username":"p12345678","password":"mypassword"}' http://45.139.50.232/authv3/generateToken` for example but that doesn't work.

Any help/clue would be greatly appreciated to fix [this issue](https://github.com/qdm12/gluetun/issues/236) 😉 

Thank you in advance!

**Comment by g00nix** [comment]
When already connected to the VPN server, the meta service listens on `https://10.0.0.1`. We should add that to the ReadMe.

**Comment by qdm12** [comment]
That worked, thanks a lot for your answer! Have a good weekend!

**Comment by qdm12** [comment]
One more question related to this, how should we handle the tls certificate `ca.ras.4096.crt` to access https://10.0.0.1 over TLS?
I tried using the certificate specifying the IP `10.0.0.1` as SAN on the client side, and get the error `x509: cannot validate certificate for 10.0.0.1 because it doesn't contain any IP SANs`. I guess I should use a hostname to validate against, but I'm not sure how to get it once I'm connected in a 'generic way', any clue would be appreciated 😉  Thanks!

**Comment by g00nix** [comment]
> One more question related to this, how should we handle the tls certificate `ca.ras.4096.crt` to access https://10.0.0.1 over TLS?

It's the same as for the VPN server you already connected to. So for example, if you connected to `wakanda420` on  IP `100.100.100.20`, you will be able to access the meta service on `10.0.0.1` with the CN/SAN `wakanda420` and the [4096 cert](https://raw.githubusercontent.com/pia-foss/manual-connections/master/ca.rsa.4096.crt).

**Comment by qdm12** [comment]
Thanks @g00nix 

I'm just having a tiny bit of trouble figuring out how to set the CN for the certificate, maybe you could help?
I have these [4 lines](https://github.com/qdm12/gluetun/pull/259/files#diff-08d822d661bf51f7f8d609299fa0b5b0R261-R264):

```go
	certificate.Subject.CommonName = commonName
	certificate.Issuer.CommonName = commonName
	certificate.DNSNames = []string{commonName}
	certificate.IPAddresses = []net.IP{{10, 0, 0, 1}}
```

where `certificate` is the x509 parsed certificate from your ca.rsa.4096.crt file and `commonName` is in my case `berlin410` as I'm using the `DE Berlin` region. The error I get every time is

```
Get "https://p46xxxxx:***@10.0.0.1/authv3/generateToken": x509: cannot validate certificate for 10.0.0.1 because it doesn't contain any IP SANs
```

By the way, there is already a bunch of users of PIA and my container that are quite happy with the port forwarding setup for your nextgen servers, so a big thanks for helping! And the persistent port forwarded is certainly an extra goodie too!

Thank you in advance!

**Comment by g00nix** [comment]
@qdm12 that is because Go 1.15 doesn't accept certificates that do not contain SAN, as per https://tools.ietf.org/html/rfc6125#section-6.5.1

This RFC has been there since 2011, but everybody decided to ignore it and suddenly in 2020 multiple languages started to reject certificates that do not have SAN, as the CN is not enough for a verification. We already started a process to add SAN to all certificates, but it seems that not all meta services contain it at this point.

Can you please go for `&tls.Config{InsecureSkipVerify: true}` for now? I will have a look at all certificates and make sure they all have SAN, but this will take some time due to other more pressing issues.

**Comment by qdm12** [comment]
Today I learnt 👍!

Yes I was using `InsecureSkipVerify` already and that works, at least it's encrypted 😉

No pressure for adding the SAN, but thank you for adding it to your backlog!

That will be all for now, thank you again.

**Comment by qdm12** [comment]
I tried with Go 1.14 where the RFC isn't enforced, but I still get the same error message, so maybe that's an issue on my client side. In case that can help you investigate further in the future. Again, no pressure.

I also tried without success with minimum TLS version of 1.0, setting the subject and issuer common name to `berlin410` as well as setting `berlin410` in the list of DNS names of the certificate:

```go
const certificateBase64 := "MIIHqzCCBZOgAwIBAgIJAJ0u+vODZJntMA0GCSqGSIb3DQEBDQUAMIHoMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExEzARBgNVBAcTCkxvc0FuZ2VsZXMxIDAeBgNVBAoTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAwHgYDVQQLExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEAxMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxIDAeBgNVBCkTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMS8wLQYJKoZIhvcNAQkBFiBzZWN1cmVAcHJpdmF0ZWludGVybmV0YWNjZXNzLmNvbTAeFw0xNDA0MTcxNzQwMzNaFw0zNDA0MTIxNzQwMzNaMIHoMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExEzARBgNVBAcTCkxvc0FuZ2VsZXMxIDAeBgNVBAoTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAwHgYDVQQLExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEAxMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxIDAeBgNVBCkTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMS8wLQYJKoZIhvcNAQkBFiBzZWN1cmVAcHJpdmF0ZWludGVybmV0YWNjZXNzLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALVkhjumaqBbL8aSgj6xbX1QPTfTd1qHsAZd2B97m8Vw31c/2yQgZNf5qZY0+jOIHULNDe4R9TIvyBEbvnAg/OkPw8n/+ScgYOeH876VUXzjLDBnDb8DLr/+w9oVsuDeFJ9KV2UFM1OYX0SnkHnrYAN2QLF98ESK4NCSU01h5zkcgmQ+qKSfA9Ny0/UpsKPBFqsQ25NvjDWFhCpeqCHKUJ4Be27CDbSl7lAkBuHMPHJs8f8xPgAbHRXZOxVCpayZ2SNDfCwsnGWpWFoMGvdMbygngCn6jA/W1VSFOlRlfLuuGe7QFfDwA0jaLCxuWt/BgZylp7tAzYKR8lnWmtUCPm4+BtjyVDYtDCiGBD9Z4P13RFWvJHw5aapx/5W/CuvVyI7pKwvc2IT+KPxCUhH1XI8ca5RN3C9NoPJJf6qpg4g0rJH3aaWkoMRrYvQ+5PXXYUzjtRHImghRGd/ydERYoAZXuGSbPkm9Y/p2X8unLcW+F0xpJD98+ZI+tzSsI99Zs5wijSUGYr9/j18KHFTMQ8n+1jauc5bCCegN27dPeKXNSZ5riXFL2XX6BkY68y58UaNzmeGMiUL9BOV1iV+PMb7B7PYs7oFLjAhh0EdyvfHkrh/ZV9BEhtFa7yXp8XR0J6vz1YV9R6DYJmLjOEbhU8N0gc3tZm4Qz39lIIG6w3FDAgMBAAGjggFUMIIBUDAdBgNVHQ4EFgQUrsRtyWJftjpdRM0+925Y6Cl08SUwggEfBgNVHSMEggEWMIIBEoAUrsRtyWJftjpdRM0+925Y6Cl08SWhge6kgeswgegxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTETMBEGA1UEBxMKTG9zQW5nZWxlczEgMB4GA1UEChMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxIDAeBgNVBAsTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAwHgYDVQQDExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEKRMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRlaW50ZXJuZXRhY2Nlc3MuY29tggkAnS7684Nkme0wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOCAgEAJsfhsPk3r8kLXLxY+v+vHzbr4ufNtqnL9/1Uuf8NrsCtpXAoyZ0YqfbkWx3NHTZ7OE9ZRhdMP/RqHQE1p4N4Sa1nZKhTKasV6KhHDqSCt/dvEm89xWm2MVA7nyzQxVlHa9AkcBaemcXEiyT19XdpiXOP4Vhs+J1R5m8zQOxZlV1GtF9vsXmJqWZpOVPmZ8f35BCsYPvv4yMewnrtAC8PFEK/bOPeYcKN50bol22QYaZuLfpkHfNiFTnfMh8sl/ablPyNY7DUNiP5DRcMdIwmfGQxR5WEQoHL3yPJ42LkB5zs6jIm26DGNXfwura/mi105+ENH1CaROtRYwkiHb08U6qLXXJz80mWJkT90nr8Asj35xN2cUppg74nG3YVav/38P48T56hG1NHbYF5uOCske19F6wi9maUoto/3vEr0rnXJUp2KODmKdvBI7co245lHBABWikk8VfejQSlCtDBXn644ZMtAdoxKNfR2WTFVEwJiyd1Fzx0yujuiXDROLhISLQDRjVVAvawrAtLZWYK31bY7KlezPlQnl/D9Asxe85l8jO5+0LdJ6VyOs/Hd4w52alDW/MFySDZSfQHMTIc30hLBJ8OnCEIvluVQQ2UQvoW+no177N9L2Y+M9TcTA62ZyMXShHQGeh20rb4kK8f+iFX8NxtdHVSkxMEFSfDDyQ="
certificateBytes, err := base64.StdEncoding.DecodeString(certificateBase64)
if err != nil {
	panic(err)
}
certificate, err := x509.ParseCertificate(certificateBytes)
if err != nil {
	panic(err)
}
certificate.Subject.CommonName = "berlin410"
certificate.Issuer.CommonName = "berlin410"
certificate.DNSNames = []string{"berlin410"}
rootCAs := x509.NewCertPool()
rootCAs.AddCert(certificate)
TLSClientConfig := &tls.Config{
	RootCAs:    rootCAs,
	MinVersion: tls.VersionTLS10,
}
```

**Comment by qdm12** [comment]
Hm I'm trying with [this](https://github.com/qdm12/gluetun/pull/259/commits/48d042f9671667e3cc333d32c69303a94aeac0ec#diff-caa4b12e4ca9ecec71d5d219b956b9e958544e86edb998a72f4a0cb9289fc8dcR263) using Go 1.14:

```go
certificate.Subject.CommonName = commonName
certificate.Issuer.CommonName = "Private Internet Access"
```

But it still gives the same error `x509: cannot validate certificate for 10.0.0.1 because it doesn't contain any IP SANs`. Anyway, that's fine I guess, we can wait for you to add SAN to your certificates in the future.

**Comment by qdm12** [comment]
Alright found the bug, I had to set the common name elsewhere in my code, sorry for diverging a bit. Now I get the SAN error when using Go 1.15 `x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`. For now I will use that `GODEBUG` variable until you add SAN to your certificate. Thank you again for all your help.

**Comment by g00nix** [comment]
I will probably forget to tell you when all certs will have SAN, as it will probably take months to upgrade all servers in the fleet. If you can survive with `x509ignoreCN` for now, that is great.

**Comment by L11R** [comment]
@qdm12 you don't need to touch certificate at all. Just write your own `DialContext` for `*http.Transport`. Example:
```golang
// Custom dial context
dialer := &net.Dialer{
	Timeout:   30 * time.Second,
	KeepAlive: 30 * time.Second,
}
tr.DialContext = func(ctx context.Context, network, addr string) (net.Conn, error) {
	value := ctx.Value("resolve")
	if value != nil {
		value, ok := ctx.Value("resolve").(string)
		if !ok {
			return nil, errors.New("invalid input")
		}
		return dialer.DialContext(ctx, network, value)
	}
	return dialer.DialContext(ctx, network, addr)
}
```
And request itself:
```golang
u := &url.URL{
	Scheme:      "https",
	User:        url.UserPassword(username, password),
	Host:        commonName,
	Path:        "/authv3/generateToken",
}
req, err := http.NewRequest(http.MethodGet, u.String(), nil)
if err != nil {
	return "", err
}
req = req.WithContext(context.WithValue(context.Background(), "resolve", ip + ":443"))
resp, err := c.HTTPClient.Do(req)
if err != nil {
	return "", err
}
defer resp.Body.Close()
```

Now you automatically substitute IP and don't give golang to resolve DNS by itself.

**Comment by qdm12** [comment]
@L11R But does that do any TLS validation?

For now I have it setup with Go 1.15 and the GODEBUG environment variable mentioned above which would allow the current program version to take advantage of the SAN for TLS verification by clearing GODEBUG, once SAN is added to the certificate in the future.

What would be the advantages of your method?

**Comment by L11R** [comment]
@qdm12 of course it does. It works like entries from /etc/hosts.

**Comment by qdm12** [comment]
Oh I see, so you flip around the IP address with the server name essentially, and the server name gets substituted with the IP address when dialing. Sorry I didn't get your point before. So that means there would be no advantage in using SAN for the certificate in this situation right?

PS: Sorry for the spamming in the issue

**Comment by L11R** [comment]
@qdm12 I guess yes.

**Comment by qdm12** [comment]
Hello @L11R I tried your way (in this [not-too-long PR](https://github.com/qdm12/gluetun/pull/264/files#diff-caa4b12e4ca9ecec71d5d219b956b9e958544e86edb998a72f4a0cb9289fc8dcR262)) but we still get the same x509 SAN error unfortunately 😕
