### ISSUE TITLE
PIA_DNS flag is lost when using setup script

### ISSUE THREAD

**Issue by dom11990** [pia-foss/manual-connections#101]
Hello,

I noticed that the PIA_DNS=true env variable is not included in the string that is spit out at the end of the run_setup.sh (or rather the get_region.sh script). It looks like the connect_to_openvpn_with_token.sh script supports this flag, was there a reason it was not included? Is it an oversight or am I missing something?

cheers
dominik

**Comment by faireOwl** [comment]
This is intentional — altering DNS settings early not be prudent, in the event that the script is terminated before completion. Additionally, PIA DNS servers can only be accessed within the VPN tunnel, so alterations to the DNS settings are not invoked until the connection.
