### ISSUE TITLE
No internet connection via pia wireguard interface

### ISSUE THREAD

**Issue by pkrack** [pia-foss/manual-connections#108]
Hi,
I hope this is not the wrong place as it is not an issue with your repo but a question.
I wrote a script to only connect create a wireguard interface, using systemd's netdev and network files.

The most relevant part I guess is here:
```
echo "
[NetDev]
Name=pia
Kind=wireguard
Description=PIA tunnel

[WireGuard]
PrivateKey=$priv_key

[WireGuardPeer]
PublicKey=$(echo "$wireguard_json" | jq -r '.server_key')
AllowedIPs=0.0.0.0/0
Endpoint=$(echo "$wireguard_json" | jq -r '.server_ip'):$(echo $wireguard_json | jq -r '.server_port')
PersistentKeepalive=25
" > $netdev_file

# TODO: compute prefix length from my ip and .server_vip
echo "
[Match]
Name=pia

[Network]
Address=$(echo "$wireguard_json" | jq -r '.peer_ip')/18
DNS=$(echo "$wireguard_json" | jq -r '.dns_servers[0]')
" > $network_file
```
I then call networkctl reload and my interface is created correctly.
however, if I set my default route to $(echo $wireguard_json | jq -r '.server_vip'), I do not have internet access anymore. 
e.g. ping -4 google.com or ping -4 $(echo $wireguard_json | jq -r '.server_vip') does not work

Note that I just set the prefix to 18 in the script, but I noticed that different prefixes seem to be used, and fixed it manually in the .network file by using an IP calculator tool to find out which prefix results in .server_ip being the first IP address in the subnet.

an example output from sudo wg show pia suggesting at least something is working:
```
interface: pia
  public key: TLuop6M6QgOgbaN5QzbJiOI5EDLKmBF9aktbaNUYP0I=
  private key: (hidden)
  listening port: 52716

peer: diNrcdE1lLv7ZThTbBRbsNF/bFq1+mgwUKcsEtZC4ng=
  endpoint: 212.102.37.56:1337
  allowed ips: 0.0.0.0/0
  latest handshake: 27 minutes, 21 seconds ago
  transfer: 184 B received, 363.96 KiB sent
  persistent keepalive: every 25 seconds
```

Any ideas on what I am doing wrong? Or my why this obviously should not work?
Thank you very much in advance :)

For completeness here is the entire script:
[myscript.zip](https://github.com/pia-foss/manual-connections/files/6214133/myscript.zip)

**Comment by g00nix** [comment]
Why don't you just use `/etc/wireguard/`, as describe [here](https://github.com/pia-foss/manual-connections/blob/master/connect_to_wireguard_with_token.sh)?

**Comment by pkrack** [comment]
My goal is to set up a split tunnel with cgroups to set up different routes based on which cgroup an application is running in.

I would then like to do things like make a service depend on the .netdev and .network files for pia. 

Using wg-quick would also work but I would prefer managing my entire network configuration with systemd-networkd. It's probably a bit capricious but I would like to have a setup as clean (and 'clean' is opinionated here) as possible.

I understand if you don't have time for this, just close the issue in that case, I will settle for wg-quick :) I just thought I'd ask to see if someone sees an obvious mistake and because I did not know where else I could ask for help! :)

**Comment by g00nix** [comment]
You are right, this is a bit out of the scope of this repository. The split tunneling behavior you are looking for is offered by the Desktop Apps.

Considering you want to go into the details and create a setup according to your preferences, I think you should pursue this with systemd-networkd and WireGuard documentation (and maybe tickets on those repos). We offer WireGuard servers and documentation on how to consume these servers, but do not cover custom client setups. Considering the high variety of client setups, it is not possible to provide support for all the possible combinations.

I would personally start with these articles (though I have a feeling you already checked these):

- https://wiki.archlinux.org/index.php/WireGuard#systemd-networkd
- https://wiki.archlinux.org/index.php/Systemd-networkd
- https://man.archlinux.org/man/systemd.network.5
- https://www.freedesktop.org/software/systemd/man/systemd.netdev.html

**Comment by pkrack** [comment]
I'm familiar with these articles, but thank you very much for going through the trouble to compile them here.
I will go annoy the people over at the wireguard repo next probably! Thank you for your help :)

**Comment by lmakarov** [comment]
@pkrack were you able to figure this out?

I'm battling with a PIA wireguard configuration for my router.
I tried multiple variations of the PIA scripts (including this official repo). I get a seemingly valid pia.conf for wireguard, connect and... nothing - `transfer: 0 B received`:

```
user@ubuntu:~/manual-connections$ sudo wg show pia
interface: pia
  public key: DW5oD+bGcVJwyZYobguTe8PQ2+W3Ug5FvwqHHjL9IyY=
  private key: (hidden)
  listening port: 44139
  fwmark: 0xca6c

peer: ioPl8Bd2ajZqMQbyxPJZ8vFUwRUuI0JBSB00QLdHIFY=
  endpoint: 191.96.106.243:1337
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 740 B sent
  persistent keepalive: every 25 seconds
```

Tried on Ubuntu, Mac, Android, different networks. The official PIA client works just fine on Mac/Android using wireguard protocol.

cc @g00nix
