### ISSUE TITLE
2FA / Two Factor Authentication

### ISSUE THREAD

**Issue by MitchTalmadge** [pia-foss/manual-connections#109]
Hey there! Thanks for the scripts.

I am trying to use `get_token.sh` without luck and I am worried that it is because I use 2FA on my PIA account.

```
# PIA_USER="..." PIA_PASS="..." ./get_token.sh
Could not authenticate with the login credentials provided!
```

I have double checked that my credentials are correct. Does anything special need to be done for 2FA accounts? 

Thanks.

**Comment by HazMatt69** [comment]
Hi,

I'm having sort of the same issue. Since yesterday my credentials don't work anymore using the script, while they work fine using the app

**Comment by g00nix** [comment]
> I'm having sort of the same issue. Since yesterday my credentials don't work anymore using the script, while they work fine using the app

@HazMatt69 We actually need more information in order to troubleshoot your case, and since this is a public repository, this is not the best place to troubleshoot issues that affect only specific accounts. Please open a ticket with support and ask for Joseph.

**Comment by HazMatt69** [comment]
@g00nix Will do! Thx!

**Comment by faireOwl** [comment]
Confirm that your system is using jq 1.6 and not a previous version. Even if jq 1.6 is present on your system, you may be using 1.5 by default, which can cause the issue you have reported.

**Comment by HazMatt69** [comment]
@faireOwl That was indeed the issue!
Thx!

**Comment by g00nix** [comment]
This looked at first like a problem with the servers which is actually out of the scope of this client-side repo. as we now know there is no problem with the servers or with the repo, this ticket can be closed.
