### ISSUE TITLE
authenticated failed

### ISSUE THREAD

**Issue by steff2632** [pia-foss/manual-connections#110]
having trouble authenticating.

when using the `10.0.0.1/authv3/generateToken` endpoint I get a 502 html error & when I use `https://privateinternetaccess.com/gtoken/generateToken` endpoint then I get an auth error. Both attempts are from inside the vpn

is there something else I should be doing

`curl -v -ks -u "USERNAME:PASSWORD" --max-time 10 "https://privateinternetaccess.com/gtoken/generateToken"`

**Comment by g00nix** [comment]
Is 2FA enabled on your account?

**Comment by steff2632** [comment]
no. Its the same username/password used to connect to the vpn initially

**Comment by g00nix** [comment]
are you sure the credentials didn't just expire?

**Comment by steff2632** [comment]
no, because they work in the PIA App on my MacBook, & work for the OpenVPN connection. It must be the curl command, however it used to work as it is so somethings changed on the PIA side regarding token/authentication

**Comment by g00nix** [comment]
>  somethings changed on the PIA side regarding token/authentication

Actually nothing changed. This still works:
```
curl -u "p0123456:xxxxxxxxxxx" "https://privateinternetaccess.com/gtoken/generateToken"
{
    "status": "OK",
    "token": "xxxxxxxxxxxxxxxxx"
}
```

I think that more information is needed in order to troubleshoot this case, and since this is a public issue in github, it would be better if you opened a ticket with CS. Please ask for Joseph in the ticket.

**Comment by steff2632** [comment]
my password has auto generated & has a "!" & a "#" in it, do they have to be escaped at all? have escaped the "!" from the CLI but is further escapes needed?

**Comment by faireOwl** [comment]
Upon testing this, I can confirm that '!' needs the escape but the other two characters do not, and that this call works fine.

If you are having issues, it is likely related to your max-wait or DNS settings.
