### ISSUE TITLE
getSignature Error

### ISSUE THREAD

**Issue by VR-Punk** [pia-foss/manual-connections#114]
hello,

i got a pia token with

PIA_USER=p0123456 PIA_PASS=xxx ./get_token.sh

and want to get signature

curl -k "https://10.4.128.1:19999/getSignature?token=$TOKEN"

but get this error
{
    "status": "ERROR",
    "message": "Unauthorized client"
}

**Comment by faireOwl** [comment]
The scripts would not require use of manual curl commands and none of the documentation instructs doing so. Be sure to use the documentation provided and read the on-screen output that is provided by the scripts.

If you need additional assistance, here is a video that provides an introduction to using the scripts: https://www.youtube.com/watch?v=Sq8T7oBog44
