### ISSUE TITLE
How to addKey in Flutter Dio

### ISSUE THREAD

**Issue by linmq** [pia-foss/manual-connections#118]
`echo Trying to connect to the PIA WireGuard API on $WG_SERVER_IP...`
`wireguard_json="$(curl -s -G \`
`  --connect-to "$WG_HOSTNAME::$WG_SERVER_IP:" \`
`  --cacert "ca.rsa.4096.crt" \`
`  --data-urlencode "pt=${PIA_TOKEN}" \`
`  --data-urlencode "pubkey=$pubKey" \`
`  "https://${WG_HOSTNAME}:1337/addKey" )"`
`export wireguard_json`

The code above is to add WireGuard public key to the PIA server, I try to do the same thing on Flutter with [Dio](https://github.com/flutterchina/dio), but it ouput an error
`CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:354))`

Any help would be appreciated

**Comment by linmq** [comment]
Looks like it cannot do this on Dart
https://github.com/dart-lang/sdk/issues/36551

**Comment by faireOwl** [comment]
This inquiry does not appear to be related to this github project.

This platform is for reporting issues with the expected function of the current script versions — to seek assistance with mediating manual Wireguard connections without using these scripts, or report issues with third party scripts you would need to use other resources.
