### ISSUE TITLE
Choosing wrong server

### ISSUE THREAD

**Issue by glorious1** [pia-foss/manual-connections#119]
The scripts used to always choose the Vancouver server, which is closest and lowest latency.  Now for some reason it is always choosing Panama.  I don't understand why.

I'm using a slightly modified version of the scripts, but did not touch that logic.

Here's what I'm getting in log.  Any ideas?

```
################################
    get_region_and_token.sh
################################

Getting the server list... OK!
Port Forwarding is enabled, so regions that do not support
port forwarding will get filtered out.
Testing regions that respond faster than 0.1 seconds:
Got latency 87200s for region: Bahamas (geo)
Got latency 81366s for region: CA Toronto
Got latency 65811s for region: CA Montreal
Got latency 9484s for region: CA Vancouver
Got latency 70203s for region: CA Ontario
Got latency 89107s for region: Greenland (geo)
Got latency 96724s for region: Mexico (geo)
Got latency 44852s for region: Panama (geo)
Got latency 96403s for region: Brazil (geo)
Got latency 86435s for region: Venezuela (geo)
Got latency 99486s for region: Mongolia (geo)
The closest region is Panama (geolocated region).

The script found the best servers from the region closest to you.
When connecting to an IP (no matter which protocol), please verify
the SSL/TLS certificate actually contains the hostname so that you
are sure you are connecting to a secure server, validated by the
PIA authority. Please find bellow the list of best IPs and matching
hostnames for each protocol:
Meta Services: 91.90.126.20 // panama404
WireGuard: 91.90.126.28 // panama404
OpenVPN TCP: 91.90.126.23 // panama404
OpenVPN UDP: 91.90.126.29 // panama404
```

**Comment by g00nix** [comment]
The (geo) tag means that the server is geolocated. Probably the physical server is closer to you.

I also see you are using the old version of the script, you should try the new version by using `git pull`.

The new version of the script will guide you through forcing any region you desire.

**Comment by glorious1** [comment]
Thanks.  The pia website says the geolocated Panama server is physically in Amsterdam.  I’m in Washington state, just a few hundred km from Vancouver, BC.  Also it has the lowest latency.

I thought about pulling, and looked at some of your current scripts.  We’ve both made so many changes I think I’d have a hot mess on my hands if I pulled.  But maybe I’ll try it on a branch and see what happens.
