### ISSUE TITLE
Request: add an option to reuse the same port forward number

### ISSUE THREAD

**Issue by kreaninw** [pia-foss/manual-connections#121]
Currently, every time the script started, and if `PIA_PF=true`, the port forward will be regenerated to a new number. This behavior is making a setup to run the script on boot (before logging in) for remote SSH connection impossible since the SSH port will have to be changed accordingly to the script's newly generated port number.

Therefore I request the option to reuse the same port forward number as a feature of this script.

**Comment by g00nix** [comment]
This should already work if you have the environment variable set for `PAYLOAD_AND_SIGNATURE`:

https://github.com/pia-foss/manual-connections/blob/2e29ad2d8deaf913763c2821c4ce1de0e0e1b2eb/port_forwarding.sh#L84-L96

The scripts already give you control over this aspect. I think the scripts are documented well enough to allow you to fork this repo and extend the functionality as you desire it. Do you still think the scripts should be modified to offer a user-friendly option for this case?

**Comment by kreaninw** [comment]
> This should already work if you have the environment variable set for `PAYLOAD_AND_SIGNATURE`:
> 
> https://github.com/pia-foss/manual-connections/blob/2e29ad2d8deaf913763c2821c4ce1de0e0e1b2eb/port_forwarding.sh#L84-L96
> 
> The scripts already give you control over this aspect. I think the scripts are documented well enough to allow you to fork this repo and extend the functionality as you desire it. Do you still think the scripts should be modified to offer a user-friendly option for this case?

I could be wrong. But I think the default behavior of the script should be in line with the official PIA client where the users get the same port whenever they reconnect the connection. Moreover, the port forward is more useful this way. Otherwise, there're many settings in the system that will have to be changed accordingly to make use of the VPN's port forwarding.

My idea is that the port forward number will be reset only when the users specify `PIA_PF=false`. 

Thanks.

**Comment by g00nix** [comment]
> But I think the default behavior of the script should be in line with the official PIA client where the users get the same port whenever they reconnect the connection.

These scripts do aim to have the same behavior as the desktop app. They were written so that people can read, understand and modify them in a way that fits their requirements. I think the best option for you is to fork the scripts and to adapt them to your requirement.
