### ISSUE TITLE
How long is the connection ephemeral keypair valid for?

### ISSUE THREAD

**Issue by Arathen** [pia-foss/manual-connections#13]
Ephemeral keys are generated, and the public key added to the server using the `https://${WG_HOSTNAME}:1337/addKey` URL. 

How long is this keypair valid for, before a new one needs to be generated for a reconnection?

Thanks.

**Comment by g00nix** [comment]
As long as you are active (you have handshakes every few minutes), your key will stay there till the server gets rebooted. Though the servers can run for years, we have to reboot them for upgrades. In normal circumstances, every server will get rebooted every 3 months.

**Comment by Arathen** [comment]
Ok makes sense. Thanks.

**Comment by g00nix** [comment]
> Any idea how long you can be inactive before a key expires?

It will stay there for hours, however you shouldn't care as long as you have a keepalive for WireGuard. I will leave this ticket opened till we push keepalive here: https://github.com/pia-foss/manual-connections/blob/master/connect_to_wireguard_with_token.sh#L115-L122

That should solve any issue you might have.

**Comment by g00nix** [comment]
Keepalive got added to master: https://github.com/pia-foss/manual-connections/commit/24c7733c1449dc231b73a1ff36f4fbb996eda732

Closing ticket.
