### ISSUE TITLE
Speed expectations?

### ISSUE THREAD

**Issue by CoreyVidal** [pia-foss/manual-connections#130]
I'm posting this here because I don't know where else on the internet I'd go to discuss this (if you have any suggestions, please let me know!), but what kind of speeds should we be able to target?

I'm in Toronto with a server connected with 750/750 up/down Mbps. I'm maxing out around 42 MB/s. Should I keep optimizing my settings to try and achieve my max bandwidth? Obviously, 42 MB/s is great (350 Mbps!), but I'm able to get as much as 700 Mbps **_down_** in other applications on the same system.

**Comment by g00nix** [comment]
If you are located in the same city as the server, having a 50% speed impact is normal on OpenVPN, but on WireGuard the speed impact should be a lot smaller.

Even if I am interested in the topic, this is out of the scope of this repository. Maybe we can continue to discuss this [in private](https://t.me/gunix)?
