### ISSUE TITLE
README Suggestion: mention cloudflared as DNS-Over-HTTPS

### ISSUE THREAD

**Issue by jdkang** [pia-foss/manual-connections#131]
I would just like to make a suggestion on perhaps the README that an additional alternative setup using `resolvconf` with PIA's DNS would be using `clouldflared`'s DoH option as outlined [here](https://docs.pi-hole.net/guides/dns/cloudflared/).

It's pretty easy to setup and ostensibly mitigates ISPs from snooping.

**Comment by g00nix** [comment]
There is actually no need for doing DNS requests before establishing the VPN connection, and after the VPN connection gets established, the DNS requests are encrypted via VPN. The PIA DNS has no logs (the same as the DNS service), and all requests are anonymized before they reach the DNS service.

I personally set the PIA DNS up so I know it is secure. As I never saw the server configs from the 3rd party your recommended, I can not officially suggest that people use it for privacy-focused projects.

That being said, if you route `0.0.0.0/0` through the VPN, you can use any DNS server you want after the DNS connection is established, as your DNS requests will originate from the VPN server so they will be anonymous.
