### ISSUE TITLE
Get Token endpoint redirects to a URL which doesnt exist

### ISSUE THREAD

**Issue by hitchan** [pia-foss/manual-connections#137]
The redirect endpoint is https://www.privateinternetaccess.com/ar/gtoken/generateToken

Attempting to use the API with proper credentials results in a HTTP 404. Is there a new endpoint or something?

**Comment by g00nix** [comment]
Please pull the latest commit from the master branch. It will work as based on: https://github.com/pia-foss/manual-connections/commit/b89d7e038215a549a45de9209378275f4b946192

Please confirm this works.

**Comment by hitchan** [comment]
This endpoint does indeed work, thank you.
