### ISSUE TITLE
Create wireguard with a Dedicated IP

### ISSUE THREAD

**Issue by Casburggraaf** [pia-foss/manual-connections#141]
I have a subscription to Dedicated IP and would love to make a custiom conection through wireguard. Is there any options for this?

**Comment by g00nix** [comment]
Sadly we didn't have time to add DIP support to these scripts, but I do know of multiple people that got it working. I will sync with them to see if their scripts are ready for public use.

I am going to close this ticket, as it is a duplicate of https://github.com/pia-foss/manual-connections/issues/84

DIP support should be added as soon as possible.
