### ISSUE TITLE
Does not connect with defaults

### ISSUE THREAD

**Issue by compinche** [pia-foss/manual-connections#149]
After setup with all defaults (pressing enter for all questions), ping or traceroute to google.com  just times out.  This happens with other options selected, like selecting a specific country server, disabling IPv6, with or without PIA dns.

I want to connect to a specific country server, no IPv6, no port forwarding, Wireguard and PIA dns. After several tries and a couple of reinstalls, I decided to try the defaults with no success.
 
Using Ubuntu Server 20.04 with latest updates.

**Comment by g00nix** [comment]
Thank you for the report. We will test it out to see if we an reproduce the behavior.

**Comment by g00nix** [comment]
@compinche please `git pull` and try again.

**Comment by compinche** [comment]
It is now working for the defaults and my use case. Thank you!
