### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by qdm12** [pia-foss/manual-connections#155]
Hello there,

Recently, the certificate distributed [ca.rsa.4096.crt](https://github.com/pia-foss/manual-connections/blob/c7336e9e03087a2affe124619f4446fd4b7dd29c/ca.rsa.4096.crt#L1) fails to validate in Go:

```
x509: certificate signed by unknown authority
```

[Runnable Go code](https://go.dev/play/p/rayMo58IKhn)

It might be because of an update in system/Mozilla CAs (in my particular case, the [breml/rootcerts upgrade from v0.2.2 to v0.2.3](https://github.com/breml/rootcerts/compare/v0.2.2...v0.2.3))

Related issue: https://github.com/qdm12/gluetun/issues/958

Any idea how to fix this? Thanks!

**Comment by qdm12** [comment]
It looks like now the OS x509 certificates work to validate the server name, and there is no longer a need to use your custom x509 PEM encoded certificate, which also no longer works to validate the server name. Let me know if I missed out on something!

**Comment by g00nix** [comment]
That certificate is the root, and it's also self signed by design. Allowing VPN to be signed by 3rd parties adds an attack surface.
