### ISSUE TITLE
List of working wireguard servers

### ISSUE THREAD

**Issue by mfizz1** [pia-foss/manual-connections#157]
Is there a list of working PIA servers for wireguard. There are 100s of servers and I don't want to go through one by one to find out which one works.

Is there a way of knowing? I had switzerland working for couple of hours and now thats not working either.

TIA

**Comment by g00nix** [comment]
The list gets updated in real time. If a server is part of the list, it works. 

If the server you are connected to crashes for whatever reason, get the list again and connect to a new server. The apps get the list every 10 minutes and cache it. You can implement something similar if you want to be sure you always have servers.

**Comment by mfizz1** [comment]
What I meant was not every conf generated works first time. I may have to try 2/3 times cycling servers to get a working config file. If this is expected behaviour part of crash, fair enough.
