### ISSUE TITLE
Create just the config without opening the VPN connection

### ISSUE THREAD

**Issue by RoboMagus** [pia-foss/manual-connections#168]
It'd be great to have a script that _just_ creates the configuration files for e.g. wireguard based on the provided input / environment variables, such that the generated config file could then be used in other applications.

This should IMO be easily doable by splitting up the functionality of the `connect_to_[x]_with_token.sh` scripts.

**Comment by MitchTalmadge** [comment]
Looks like your PR was merged so this can be closed, right? Nice addition btw thank you!
