### ISSUE TITLE
Issues with xargs on FreeBSD

### ISSUE THREAD

**Issue by dundunn** [pia-foss/manual-connections#17]
Hi, thanks for the great work. I'm quite happy with the direction of this :)

I have a problems on FreeBSD though. The script isn't executing properly on FreeBSD because [`xargs`](https://www.freebsd.org/cgi/man.cgi?xargs) differs from the Linux implementation. I'm not sure if more parts are likely to fail. 
I can't find a way to replicate Linux's `xargs` behavior on FreeBSD. I'm not sure whether to take -J or -I and how the parameters should look like. 
[`xargs -I{} bash -c 'printServerLatency {}' |`](https://github.com/pia-foss/manual-connections/blob/7a76a24a7683f1b24e9d27c079437f9ded73bc9f/get_region_and_token.sh#L95)

**Comment by g00nix** [comment]
The current `xargs` command was actually suggested by @bubtheengineer as a fix for FreeBSD: https://github.com/pia-foss/manual-connections/pull/8/files

Can you please provide some logs and/or some examples of how `xargs` works on FreeBSD?

**Comment by bubtheengineer** [comment]
@dundunn What errors are you getting?  The command you posted works correctly with FreeBSD 11.3 (FreeNAS)

**Comment by dundunn** [comment]
I downloaded release v0.1.0 and changed the `xargs` line manually, that was my mistake. Sorry for the issue.
