### ISSUE TITLE
Script not executing properly with cron on FreeBSD

### ISSUE THREAD

**Issue by dundunn** [pia-foss/manual-connections#18]
The script itself is fine when I run it manually, but I would like to run it with cron in a FreeNAS jail. 
The cronjob `@reboot /usr/local/etc/manual-connections/get_region_and_token.sh >> /usr/local/etc/manual-connections/logfile` gets executed but it fails here:
https://github.com/pia-foss/manual-connections/blob/7a76a24a7683f1b24e9d27c079437f9ded73bc9f/get_region_and_token.sh#L150-L153

I set the variables `PIA_USER, PIA_PASS, PIA_AUTOCONNECT, PIA_PF` in the script. `generateTokenResponse` is empty when run with cron but the echoed curl command from [L160](https://github.com/pia-foss/manual-connections/blob/7a76a24a7683f1b24e9d27c079437f9ded73bc9f/get_region_and_token.sh#L160) is correct.

**Comment by g00nix** [comment]
> I set the variables `PIA_USER, PIA_PASS, PIA_AUTOCONNECT, PIA_PF` in the script.

Did you also export the vars?

**Comment by dundunn** [comment]
> > I set the variables `PIA_USER, PIA_PASS, PIA_AUTOCONNECT, PIA_PF` in the script.
> 
> Did you also export the vars?

Yes like this `export PIA_USER=p000000` at the start of get_region_and_token.sh. The script echoes `$ curl -vs -u p000000:00000000000 --cacert ca.rsa.4096.crt --connect-to luxembourg402::92.xxx.xx.xxx: https://luxembourg402/authv3/generateToken` to my logfile and it gives me a token when I run it. So the variables seem to be set.

**Comment by abraithwaite** [comment]
This actually sounds super similar to the issue I was having (#14) now that it's mentioned.

I wonder if its a tty vs non-tty issue?

**Comment by g00nix** [comment]
@abraithwaite are you running FreeBSD?

**Comment by mstargard** [comment]
Are you in the right directory? That curl wants ca.rsa.4096.crt in your local directory.

Maybe put a "cd /usr/local/etc/manual-connections" in the script next to your variables.

I have it running on pfSense. - M

**Comment by dundunn** [comment]
> Are you in the right directory? That curl wants ca.rsa.4096.crt in your local directory.
> 
> Maybe put a "cd /usr/local/etc/manual-connections" in the script next to your variables.
> 
> I have it running on pfSense. - M

Yes that was the problem. Thank you very much for pointing it :)

**Comment by hjaltioj** [comment]
Can someone please help me to get portforward to work on pfsense? :)

**Comment by g00nix** [comment]
> Can someone please help me to get portforward to work on pfsense? :)

Did you try one of the [3rd party repos](https://github.com/pia-foss/manual-connections#3rd-party-repositories)?

**Comment by hjaltioj** [comment]
Yeah, but cant get deluge to use ut. the repo is for transmission :/
