### ISSUE TITLE
Add an option to select the desired region

### ISSUE THREAD

**Issue by IncredibleLaser** [pia-foss/manual-connections#20]
As of now, only the fastest region can be selected by the scripts, or all server details need to be provided to the connection script. In most cases, you get your own country as a region, which makes the scripts much less useful for circumventing IP-based geolocation blocks.

Please add an option to preselect a region and skip the latency test, e.g. a variable PIA_REGION that accepts the country code for the desired region.

**Comment by g00nix** [comment]
There actually was a [PR](https://github.com/pia-foss/manual-connections/pull/6) for that. No idea why, but it got closed before I got to merge it.

This feature is highly required. It will get added soon enough.

**Comment by g00nix** [comment]
This will come with version v2.0.0

**Comment by g00nix** [comment]
Please check https://github.com/pia-foss/manual-connections/pull/52

**Comment by g00nix** [comment]
Please check https://github.com/pia-foss/manual-connections/tree/v2.0.0

**Comment by g00nix** [comment]
Solved in release [v2.0.0](https://github.com/pia-foss/manual-connections/tree/v2.0.0).
