### ISSUE TITLE
get_region_and_token.sh fails because of using default locale

### ISSUE THREAD

**Issue by solsticedhiver** [pia-foss/manual-connections#22]
When running `./get_region_and_token.sh`, one gets:

```
Getting the server list... OK!                                                      
Testing regions that respond faster than 0.05 seconds:
curl: option --connect-timeout: expected a proper numerical parameter
curl: try 'curl --help' for more information
curl: option --connect-timeout: expected a proper numerical parameter
curl: try 'curl --help' for more information
curl: option --connect-timeout: expected a proper numerical parameter
curl: try 'curl --help' for more information

```
and the list of errors never ends

curl excepts a numerical value (not a float) as `--connect-timeout` value. But the default one specifed in the script is **0.05**. This is wrong

using curl 7.73 on archlinuxarm

This works better with for example `MAX_LATENCY=1 ./get_region_and_token.sh`

**Comment by solsticedhiver** [comment]
OK.
I am using the default locale fr_FR.UTF-8 and guess what I have to use a localized float number aka

MAX_LATENCY=0,05 ./get_region_and_token.sh

So the script could may be switch a default locale like C ??

**Comment by g00nix** [comment]
@solsticedhiver please check with `LC_NUMERIC=en_US.utf8` and let me know if this solves the issue.

**Comment by solsticedhiver** [comment]
@g00nix yes that works fine with `LC_NUMERIC=en_US.utf8`

**Comment by g00nix** [comment]
@solsticedhiver please test the master branch

**Comment by solsticedhiver** [comment]
y e s

**Comment by g00nix** [comment]
This should solve it for all the European locale settings.
