### ISSUE TITLE
pia-foss/manual-connections repository confirmed to work on Raspberry Pi OS 2020-08-20

### ISSUE THREAD

**Issue by eggplant37** [pia-foss/manual-connections#29]
Here's another system to add to the confirmed working list:

Raspberry Pi OS 2020-08-20 running on Raspberry Pi 4B board.

**Comment by g00nix** [comment]
@eggplant37 can you please confirm if you tested both OpenVPN and WireGuard?

**Comment by eggplant37** [comment]
I've only tested OpenVPN thus far as I've not worked with WireGuard.

R

**Comment by eggplant37** [comment]
I've had some time to put up WireGuard on another Raspberry Pi 4B with
Raspberry PI OS 2020-08-20. It works just fine!

R

**Comment by taylorcox75** [comment]
Raspberry pi 4 4gb running  bullseye and openvpn method and wire guard works. 

A decent sized docker project implemented some of your port-fowarding script which works as well (getting open port on torrent client). They still have to implement the dynamic get_region functionality. Right now in docker build you have to specify a region. 

Right now it's pulling next gen servers from https://www.privateinternetaccess.com/openvpn/openvpn-(ip/tcp/strong)-nextgen.zip

https://github.com/haugene/docker-transmission-openvpn/issues/1334

https://github.com/haugene/docker-transmission-openvpn/issues/1423

Then using the function in this project to get a token and keep a port alive.

**Comment by g00nix** [comment]
@eggplant37 thank you confirming Raspberry PI. I will add it to the readme.
