### ISSUE TITLE
port forwarding REST api 19999/getSignature returns null response

### ISSUE THREAD

**Issue by diablodale** [pia-foss/manual-connections#32]
Hello. When running `get_region_and_token.sh` with `PIA_PF=true`, the REST api at `:19999/getSignature` fails to return any result. This appears to be a timing issue.

### Setup

* commit 82ebed7c9c83988eedd04cd634a94b7f9b6394af
* Alpine linux 3.12 docker container
* set env vars `PIA_AUTOCONNECT=wireguard` `PIA_PF=true` `PIA_USER=xxxx` `PIA_PASS=yyyy`

### Repro

https://github.com/pia-foss/manual-connections/blob/d85aaf34df1336ed122525a48c74e155d1dcd833/port_forwarding.sh#L58-L64

That curl returns null. Absolutely nothing. However, if I insert a `sleep 10s` before line 59, then this REST call succeeds and returns useful results. It is unclear the actual needed delay.

**Comment by g00nix** [comment]
We also noticed this random behavior. That sleep makes a lot of sense and I think it's a great idea. I suspect the WireGuard connection doesn't get fully initiated before the curl tries to reach the PF API. I am sure there is a _very_ scientific reason behind this.

I will push a small sleep to master and close the ticket.
