### ISSUE TITLE
Cannot run these scripts inside a FreeNAS Jail (!#/bin/bash does not exist)

### ISSUE THREAD

**Issue by Mannekino** [pia-foss/manual-connections#33]
I'm unable to run these scripts inside my FreeNAS Jail for Transmission. After some digging I found that `#!/bin/bash` isn't available inside the Jail. For additional information see:

https://www.truenas.com/community/threads/startup-scripts-finally-working.71459/#post-494560

https://rainbowhackerhorse.github.io/bash-Is-Not-sh/

I changed the `#!/bin/bash` line to `#!/usr/bin/env bash` and now the scripts run. I don't know if this is something that needs to be changed in the scripts of maybe a special version for FreeBSD/FreeNAS/Jails?

**Comment by g00nix** [comment]
@Mannekino You are right, `#!/usr/bin/env bash` is needed on FreeBSD. Do you think it would be ok to centralize all FreeBSD problem in ticket #30? That way, the people start working on porting the scripts to FreeBSD can find everything they need on one single ticket.

**Comment by Mannekino** [comment]
Yes, that would be a good idea. Continue in that one. Close this one.
