### ISSUE TITLE
Questions about information API URL

### ISSUE THREAD

**Issue by qdm12** [pia-foss/manual-connections#4]
Hello there,

Thanks a lot for this repository, it's definitely useful, especially for the port forwarding part.
I have one simple to answer question regarding the API url https://serverlist.piaservers.net/vpninfo/servers/ because I need to support both v3 and v4 PIA servers, ideally (for [this project](https://github.com/qdm12/gluetun)).

I noticed you can access it through [https://serverlist.piaservers.net/vpninfo/servers/v4](https://serverlist.piaservers.net/vpninfo/servers/v4) and [https://serverlist.piaservers.net/vpninfo/servers/v3](https://serverlist.piaservers.net/vpninfo/servers/v3).

1. Is the v4  giving the nextgen v4 servers information and v3 the older servers?
1. The ports from the groups don't match what you have in your openvpn zip files (such as [https://www.privateinternetaccess.com/openvpn/openvpn-ip-nextgen.zip](https://www.privateinternetaccess.com/openvpn/openvpn-ip-nextgen.zip), is this expected? Will, for example port `1198` (UDP normal encryption), work on them still?
1. I noticed the hostnames have the domain **privacy.network** even for v3 servers, can we now safely assume all hostnames changed to *.privacy.network for the older v3 servers too?

Thank you in advance!

**Comment by g00nix** [comment]
> * Is the v4  giving the nextgen v4 servers information and v3 the older servers?

Both `v3` and `v4` give NextGen Servers. `v3` does not have meta tags. We recently introduced meta tags for added functionality. 

When using `v4`, you will get a list of meta tags which you can use to get the new authentication token, which provides faster authentication. [Here](https://github.com/pia-foss/manual-connections/blob/9a3d77ac4ed00ecb33b299eecaf2c160cdbe6895/get_region_and_token.sh#L131-L136) is an example on how to get the the token. For OpenVPN, put half of the token in the username and the other half in the password. All this will be exemplified when we finish the OpenVPN scripts.

> * The ports from the groups don't match what you have in your openvpn zip files (such as https://www.privateinternetaccess.com/openvpn/openvpn-ip-nextgen.zip, is this expected? Will, for example port `1198` (UDP normal encryption), work on them still?

The NextGen tutorial for OpenVPN from the website works, yes. I am thinking about how to add scripts for OpenVPN for this repo and also keep the user-friendly way this works for WireGuard.

The ports on the website are dedicated for native clients, however the serverlist gives the ports available for the official PIA applications. For native connections, please use the tutorial on the website till we finish this project with examples for OpenVPN.
 
> * I noticed the hostnames have the domain **privacy.network** even for v3 servers, can we now safely assume all hostnames changed to *.privacy.network for the older v3 servers too?

`v3` is the version of the server list, not the version of the servers. `privacy.network` is the domain for NextGen and it is there just in case people really need to use DNS to connect. We are starting to move everything away from the DNS, as it has delays in propagating the correct information. Please use the IPs you get in the server list and not the ones you get in the DNS, as the server list gets the new data a lot faster and has a better algorithm for providing load balancing.

**Comment by g00nix** [comment]
@qdm12 can this issue be closed?

**Comment by qdm12** [comment]
Hello @g00nix thank you so much for the quite detailed answer. I should be good to go 👍

> Please use the IPs you get in the server list and not the ones you get in the DNS

Funnily enough, that's why I was asking. I am currently extracting the IP addresses from your openvpn zip files and hardcoding the resulting IP addresses in that Docker image I'm working on, so that users don't need to rely on their DNS setup when running the container. I'll now definitely use that endpoint to update your nextgen v4 servers IP addresses, although I'll keep using the zip file approach for your older v3 servers.

Anyway, a big thanks for your work and help 💯

**Comment by fcastilloec** [comment]
I'm guessing I can hardcode any IP addresses return by `v4` list of servers. How can we get notified if there's ever a `v5` (or any future version) of the server list?

Also, what does `auto_region` refers to? It seems all servers have that field as `true`

Last, given that all the servers domains end with `.privacy.network` does it mean that all servers returned by `v4` are NextGen and the list doesn't contain any older "CurrentGen" servers?

**Comment by qdm12** [comment]
> Last, given that all the servers domains end with .privacy.network does it mean that all servers returned by v4 are NextGen and the list doesn't contain any older "CurrentGen" servers?

Yes: no current gen (v3) servers on this API endpoint it seems weather you use the /v3/ or /v4/ uri path.

**Comment by g00nix** [comment]
> I'm guessing I can hardcode any IP addresses return by `v4` list of servers. How can we get notified if there's ever a `v5` (or any future version) of the server list?

v5 is planned and will have provide 3 servers per protocol, instead of 1 server per protocol. The first server will stil bel the best, but the 2nd and 3rd servers will be listed for reconnect just in case the 1st server is not reachable. 

I will discuss internally how we can announce when new versions of the serverlist are out.

> Also, what does `auto_region` refers to? It seems all servers have that field as `true`

 `auto_region` will be false if the entire region has some issues. The full App will avoid connecting to these regions when the user automatically connects (without picking a specific region). I am not sure if this should also be added these scripts, but I will think about it.
 
> Last, given that all the servers domains end with `.privacy.network` does it mean that all servers returned by `v4` are NextGen and the list doesn't contain any older "CurrentGen" servers?

The `serverlist.piaservers.net/vpninfo/servers/` API will return only NextGen servers. Live versions in the apps are v3 and v4, but please use v4. We will upgrade these scripts to v5 as soon as it is ready for production.

We will gradually provide all the support required so that you can use only NextGen, as it has multiple improvements for security and performance. If you have troubles using NextGen, please open an issue.
