### ISSUE TITLE
/bindPort taking longer than 10 seconds

### ISSUE THREAD

**Issue by steff2632** [pia-foss/manual-connections#40]
is it normal for /bindPort to take over 10 seconds?

I have curl set to timeout after 10 seconds and lately its been failing

**Comment by iPherian** [comment]
I've also noticed timeouts on things (like getting a token). I don't know why it happens. Seems to come and go and linger for a few hours but the next day it will have gone away. It's a shame. Perhaps it also happens for my /bindPort as well ( I don't typically monitor that script ).

**Comment by g00nix** [comment]
If you are connected to a region that supports PF and you don't get an answer within 10 seconds, there is probably some issue with internet connection or with the server. This is not possible to troubleshoot without reproducing the bug and checking the server at the specific moment when the user is experiencing poor service quality.

This is also out of the scope of this repository, so all I can do is close the issue. We will keep an eye out internally and run some checks on the servers to see if we can reproduce the problem.
