### ISSUE TITLE
get_region_and_token.sh: curl default `--connect-timeout` is wrong

### ISSUE THREAD

**Issue by saveriomiroddi** [pia-foss/manual-connections#44]
Modern curl version don't support subsecond `--connect-timeout`. The default is set to 0.05, which causes a curl warning.

The default therefore needs to be raised to 1 second.

**Comment by g00nix** [comment]
> Modern curl version don't support subsecond --connect-timeout

From the [man page of the latest curl version](https://curl.se/docs/manpage.html):

```
--connect-timeout <seconds>
Maximum time in seconds that you allow curl's connection to take.
This only limits the connection phase, so if curl connects within the
given period it will continue - if not it will exit. Since version 7.32.0,
this option accepts decimal values.
If this option is used several times, the last one will be used.
```
> The default is set to 0.05, which causes a curl warning.

The warning shouldn't appear . If it does, there is some issue with bash or curl on your system. This is how normal output looks:
```
Testing regions that respond faster than 0.05 seconds:
Got latency 0.045503s for region: DE Frankfurt
Got latency 0.048684s for region: Isle of Man (geo)
Got latency 0.048116s for region: Liechtenstein (geo)
Got latency 0.030201s for region: Moldova
Got latency 0.049863s for region: Netherlands
```

> The default therefore needs to be raised to 1 second.

All regions in the world will probably respond within 350 milliseconds and most regions from the same continent should respond within 50 milliseconds. Having the limit set to 1000 milliseconds defeats the purpose of seeing only the regions that provide the best performance. If you set it to 1000, you will always see all regions and it will also make the script take a lot of time as it will have to wait a lot for all the regions from other continents.

---

Please make sure you compile curl with `c-ares` support as this 1 year old Gentoo bug points out: https://bugs.gentoo.org/699632

Solving the bug would also help other Gentoo users, but this is a Gentoo/curl bug, not a bug with this repository.

All other distros do not have this issue.
