### ISSUE TITLE
Cannot get token Cert Error

### ISSUE THREAD

**Issue by matt-lethargic** [pia-foss/manual-connections#50]
whenever I try and run the get region and token script it throws an auth error and when I try and use the curl command to debug I get

```
 error setting certificate verify locations:
  CAfile: ca.rsa.4096.crt
  CApath: /etc/ssl/certs
```

This is a fresh build of Ubuntu Server 20 with OpenVPN install

Any guidance would be great

**Comment by g00nix** [comment]
This functionality got tested on all the distributions in the README and there are forks of this code working on other platforms too. It looks like the case is isolated to your machine.

Can you please provide some more logs, maybe also with the commands you are running? Did you apply any modifications to the repo?

**Comment by matt-lethargic** [comment]
I found the answer in the end, it was because I was running it from another directory, it couldn't find the `.crt` file in the same dir as the script 👍

**Comment by kylemacey** [comment]
> I was running it from another directory, it couldn't find the `.crt` file in the same dir as the script 👍

I also ran into this. May be worth making this a little more clear around here: https://www.privateinternetaccess.com/helpdesk/news/posts/introducing-next-generation-port-forwarding
