### ISSUE TITLE
wireguard not working on RaspberryPi 4

### ISSUE THREAD

**Issue by bassamanator** [pia-foss/manual-connections#51]
Started off with an update, then did ```sudo ./run_setup.sh```.

**Settings used:**
> PIA_AUTOCONNECT=wireguard
> PIA_DNS=false
> PIA_PF=false
> MAX_LATENCY="0.05"
> Disable ip6=Yes

**This is how the install ends/errors out:**
```
...
Trying to disable a PIA WG connection in case it exists...
wg-quick: `pia' is not a WireGuard interface

Trying to write /etc/wireguard/pia.conf... OK!

Trying to create the wireguard interface...
[#] ip link add pia type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev pia
Cannot find device "pia"
```
Can this be fixed?
> RPI 4-8GB
> RaspberryPi OS 32bit
> Linux rpi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
>

**Comment by g00nix** [comment]
The script will not exist in case the PIA interface does not exist:
https://github.com/pia-foss/manual-connections/blob/338ca1ac4297abd41ba315097a458e1a27d866d1/connect_to_wireguard_with_token.sh#L100-L103

I doubt that this is the area that causes the script to fail. This will just to remove the previous connection, in case it exists. If it doesn't, it will just move forward. The only exception would be if your bash would globally set `set -e`, causing the script to exit on every error.

However there might be some other errors in the following parts of the log. I suspect `Protocol not supported` is a good hint that the kernel module for WireGuard didn't get loaded into your kernel.

**Comment by bassamanator** [comment]
Although I had access to commands such as wg and wg-quick, I don't think wireguard was installed properly from my last attemp several months ago. In any case, it's installed now and I appear to be connected to PIA via wireguard. Thanks!
