### ISSUE TITLE
Passwords containing backslash don't work.

### ISSUE THREAD

**Issue by 1wsx10** [pia-foss/manual-connections#53]
I use a password manager, and as-such my automatically generated password for PIA contained a backslash.
the bash builtin `read` interprets this as an escape sequence, causing the password to be incorrect.

solution: use `read -rs PIA_PASS` instead of `read -s PIA_PASS` to tell bash to treat the backslash like a regular character.

https://github.com/pia-foss/manual-connections/blob/cb51b0b79e9f250829baebae52029cdd83557a70/run_setup.sh#L41

**Comment by g00nix** [comment]
Can you please test the fix on multiple distros and submit a PR?

**Comment by 1wsx10** [comment]
no, sorry.

i don't have that kind of development environment setup and it would take quite a bit of effort to do that.
maybe someone who already has multiple distros available can test this.

for now, works on my machine :)

**Comment by g00nix** [comment]
I can test it myself on Arch. If somebody submits the PR, I am sure people can test it and leave a comment if it works for them.

**Comment by 1wsx10** [comment]
i was using this on raspbian, so it works there.

**Comment by g00nix** [comment]
Awesome! I saw the PR! Since the fix is that easy, we will add this to [v2.0.0](https://github.com/pia-foss/manual-connections/tree/v2.0.0).

**Comment by g00nix** [comment]
Solved as part of [v2.0.0](https://github.com/pia-foss/manual-connections/tree/v2.0.0)
