### ISSUE TITLE
Unable to connect over forwarded port via SSH

### ISSUE THREAD

**Issue by JeffreyShran** [pia-foss/manual-connections#58]
Hi,

I am able to create (I think!) a successful Wireguard connection on my cloud VPS. I have to connect to my remote server via SSH. Upon connection I get something like this and then the SSH connection stops working, which I'd expect.

```
You should consider disabling IPv6 by running:
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
Trying to connect to the PIA WireGuard API on 212.102.57.164...
{
    "status": "OK",
    "server_key": "AHrxMUhc=",
    "server_port": 1337,
    "server_ip": "212.102.57.164",
    "server_vip": "10.26.128.1",
    "peer_ip": "10.26.243.6",
    "peer_pubkey": "0A+glPEY=",
    "dns_servers": [
        "10.0.0.243",
        "10.0.0.242"
    ]
}

Trying to disable a PIA WG connection in case it exists...
wg-quick: `pia' is not a WireGuard interface

Trying to write /etc/wireguard/pia.conf... OK!

Trying to create the wireguard interface...
[#] ip link add pia type wireguard
[#] wg setconf pia /dev/fd/63
[#] ip -4 address add 10.26.243.6 dev pia
[#] ip link set mtu 1420 up dev pia
[#] wg set pia fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev pia table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
```

I set my SSH port to match the 1337 set by your script prior to connecting to the VPN which worked without issue. Then at this point I try to open a new connections via SSH to the "server_ip" 212.102.57.164. This responds back with `ssh_exchange_identification: Connection closed by remote host`.

I feel like I'm doing everything right but must have missed a fundamental step somewhere. I've ruled out any problems with the SSH config as that's what I used to connect to the VPS prior to enabling the VPN.

Can anyone help me out please? I'm happy to provide more information if needed.

For info, I'm using Debian 10.

**Comment by g00nix** [comment]
`212.102.57.164` is the servers public IP. If you want to be able to SSH into your VPS through the VPN server, you have to set up Port Forwarding.

The servers are using NAT. In your case, your virtual private IP is `10.26.243.6`, which is getting NATed to `212.102.57.164`.

**Comment by JeffreyShran** [comment]
I really appreciate the quick response. Connecting to `10.26.243.6` on that port results in a timeout. I initialised the command like this with the PF flag which I assumed turned on the port forwarding. Is there an extra step?

`PIA_TOKEN="0pcs...5vyc=" WG_SERVER_IP=212.102.57.164 WG_HOSTNAME=frankfurt410 PIA_PF=true ./connect_to_wireguard_with_token.sh`

**Comment by g00nix** [comment]
After enabling Port Forwarding, you have to try to ssh on 212.102.57.164 and the port you get from the PF script.

**Comment by JeffreyShran** [comment]
Thanks. So there is a different port number besides the one in the text in the 1st post? ` "server_port": 1337,`

I can't see anything past the point the VPN connects as it cuts the connection, so if there is a port given after that point I don't know what it is. I'd have to write a script that that would ping me on Discord or something to tell me what the port is. How would I find it?

**Comment by JeffreyShran** [comment]
I think that I understand now. I need to know what this is, right? https://github.com/pia-foss/manual-connections/blob/b355c4c66524765e146a9beb547f86b6f150a976/port_forwarding.sh#L120

**Comment by g00nix** [comment]
@JeffreyShran yes, you need to know what that is. You should have good understanding of common networking patterns before moving forward. I suggest you document yourself about the following:

- subnets
- public/private IPs
- NAT
- iptables --> tables and chains
- iptables --> NAT and masquerade

**Comment by g00nix** [comment]
We can continue the discussion as much as you want, but I will close this ticket as there is no issue with the repo.

**Comment by JeffreyShran** [comment]
Thanks for all your help @g00nix.

I understand now. Believe it or not I am familiar with those topics. Tiredness or whatever confused me regrading the hardcoded port in the script. Plus I didn't take the time to slow down and fully understand what was going on.

I'm all sorted. Thanks again! :)
