### ISSUE TITLE
Run script as a service on raspbian

### ISSUE THREAD

**Issue by Larryadd** [pia-foss/manual-connections#59]
This is more a request for help than an issue.

I managed to create a unique sh script to get the token, connect to a specified server with Wireguard and forward a port.
The script is working on my Raspberry Pi 4
I cannot manage to make it run as a service to have it start on boot (without user login) and to assign an autoreconnect script.

If someone has a solution to do it on raspbian I would really appreciate.

Thanks to all.

Larryadd.

**Comment by Larryadd** [comment]
I answer myself, there is a fork made by iPherian with everything I need.
Thanks to you iPherian !

**Comment by g00nix** [comment]
The fork from @iPherian is not marked as having anything special for Raspbian. Does this fork have any commits that fix bugs on Raspbian?

**Comment by Larryadd** [comment]
I don't think it's for raspbian specificaly but it works on it.
I have very limited knowledge in scripts in general so I'm not the right person to talk about bugs or other issues.
What I can tell is that he added a configurable .service file. it helped me to start the PIA connexion script as a service and run it at startup. this it what I was looking for.
I'm on raspbian but it clearly whould work on debian. for other distributions, I don't know.

**Comment by iPherian** [comment]
@g00nix Nothing specifically for Raspbian, I guess it just happens to be compatible. It does have a systemd service to run from startup.

@Larryadd You're welcome!

**Comment by g00nix** [comment]
In that case, anybody experiencing this issue can use https://github.com/iPherian/manual-connections
