### ISSUE TITLE
Wireguard on Romania server fails to connect

### ISSUE THREAD

**Issue by gurabli** [pia-foss/manual-connections#61]
I'm using Qbittorrent VPN container that includes PIA. I have problems with connection to Romanian server using Wireguard. All the other European servers work perfectly fine (I tried at least 6). 
The developer of the container said the issue should be raised here, as he is in no control of this part.

`Endpoint = ro.privacy.network:1337
`
Error is:
```
2020-11-24 11:18:31,621 DEBG 'start-script' stderr output:
parse error: Invalid numeric literal at line 4, column 0
2020-11-24 11:18:31,696 DEBG 'start-script' stdout output:
[warn] Unable to successfully download PIA json to generate token from URL 'https://89.38.224.170
143.244.52.1/authv3/generateToken'
[info] Retrying in 10 secs...
```
Any ideas?

**Comment by g00nix** [comment]
I see that your error is:
```
[warn] Unable to successfully download PIA json to generate token from URL 'https://89.38.224.170
143.244.52.1/authv3/generateToken'
```
This looks like a string concatenation error. It looks like you have `ip1 + "\n" + ip2`. Please ask your developer to have a look at the code.

That warning message is not a message from this repository, so I have to close this ticket.

**Comment by gurabli** [comment]
Thanks! I will and will see about the reply.
