### ISSUE TITLE
API Rate Limits

### ISSUE THREAD

**Issue by taylorcox75** [pia-foss/manual-connections#63]
Been testing a module of code for a docker container and got the following when requesting an auth token 

{
  "status": "error",
  "code": "too_many_attempts",
  "message": "Try again later."
}

When does the request limit reset?

**Comment by g00nix** [comment]
Please give more information regarding what you are trying to do, like:
- which API endpoint you are using --> Did you find that endpoint within this repo?
- the number of requests send per timeframe --> Do you really need that many requests?
- the nature of the requests (normal or malicious) --> Why did you trigger flood control?

**Comment by taylorcox75** [comment]
Closed, on my end the project had a wrong references to this project. It was implemented  very closely, and it probably due for a rewrite.  It grabs a token from
privateinternetaccess.com/api/client/v2/token 
Then uses a docker env PF_GATEWAY to get the "payload". 

Then basically using this repos port_fowarding.sh to bind the port and query it every 15 minutes. 

$bestServer_meta_hostname/authv3/generateToken

The API was https://www.privateinternetaccess.com/api/client/v2/token

**Comment by c-er** [comment]
The lockout for the same endpoint above `https://www.privateinternetaccess.com/api/client/v2/token` seems to be longer than 2 minutes now. It's pretty easy to hit when developing scripts that access the endpoint. Can we please get some official documentation of the rate limit @g00nix ?
