### ISSUE TITLE
done: rewrite pia-vpn wireguard client in pthon

### ISSUE THREAD

**Issue by milahu** [pia-foss/manual-connections#72]
shameless advertisment:
https://github.com/milahu/python-piavpn

: )

`piavpn.py` currently has 533 lines-of-code
compared to 868 lines-of-code of the bash implementation

many lines-of-code are needed/wasted on config validation (~100 lines)
and forcing hostname in http connection (~100 lines)

**Comment by g00nix** [comment]
Congrats, you won the "Who writes less lines of code" challenge. :smile: 

Do you want your repo to be part of the list of [3rd party repos](https://github.com/pia-foss/manual-connections#3rd-party-repositories) in the README?

If yes, please provide some extra information:
- supported operating systems
- scope (in your case, it seems to be to rewrite in python)
- functionality provided (OpenVPN, WireGuard, Region Selection, Port Forwarding etc)

**Comment by milahu** [comment]
> Congrats, you won the "Who writes less lines of code" challenge.

not really : /
maybe winner in shortest github filepath

166 lines in `stmty9/synology/pia_port_forward/ng-seed-port.py` --> PF
425 lines in `FingerlessGlov3s/OPNsensePIAWireguard/PIAWireguard.py` --> PF, Wireguard
533 lines in `milahu/python-piavpn/piavpn.py` --> PF, Wireguard
868 lines in `pia-foss/manual-connections/*.sh` --> PF, Wireguard, OpenVPN

> Do you want your repo to be part of the list of 3rd party repos in the README?

yes please : )

main target is linux

scope .. yea, lets say rewrite

functions? Wireguard, port forwarding, region select (#20), list regions/servers by latency (netselect), verify public IP address, verify country of IP with local geoip database, disable IPv6, pretty config file in YAML format

todo-functions: run as daemon or cron-script, run custom commands on port change (defined in config file), maybe openVPN (the dead horse in VPN)

**Comment by g00nix** [comment]
Thank you for the information. We will add the following to the 3rd party secion:

System: Linux
Fork: No
Language: Python
Scope: WireGuard, PF
Repository: https://github.com/milahu/python-piavpn

**Comment by g00nix** [comment]
Added to the new [readme](https://github.com/pia-foss/manual-connections/tree/v2.0.0).
