### ISSUE TITLE
unauthorized client on getSignature with linux rpfilter

### ISSUE THREAD

**Issue by milahu** [pia-foss/manual-connections#81]
the API endpoint at `https://${wg_server_name}:19999/getSignature` 
seems to check the client IP address
and only works when routed over the VPN tunnel

when i enable `rpfilter` in linux
(reverse path filter, to defend against IP address spoofing, default on in [NixOS](https://github.com/NixOS/nixpkgs/issues/51258#issuecomment-759381140))
and manually unblock the VPN server with `ip route add ${wg_server_ip} via 192.168.0.1`
(`192.168.0.1` is my local gateway aka router)
then the API call to `getSignature` returns: error unauthorized client

simple solution: make `getSignature` less strict

or: use the internal IP address of the server = `${server_vip}` in the `addKey` response

**Comment by g00nix** [comment]
This sounds like the Port Forwarding API is working as designed.

> simple solution: make getSignature less strict

I don't think we can do that. :smile: 

> or: use the internal IP address of the server = ${server_vip} in the addKey response

Yes, that is the correct way to use the PF API.

**Comment by milahu** [comment]
solved by using the internal IP address of the server
`${server_vip}` in the `addKey` response
for both `getSignature` and `bindPort` requests
