### ISSUE TITLE
Connecting with PIA_AUTOCONNECT=openvpn fails

### ISSUE THREAD

**Issue by burningserenity** [pia-foss/manual-connections#83]
If I connect using `get-region.sh` with the env variable PIA_AUTOCONNECT set to just OpenVPN, it will attempt to connect, but it fails at
```
cat: /opt/piavpn-manual/route_info: No such file or directory
```

This could be changed so that either the openvpn value is invalid, or have it set default configuration of UDP with standard encryption.

**Comment by g00nix** [comment]
Thank you for the bug report. As a result of your ticket, the issue got solved in [v2.0.0](https://github.com/pia-foss/manual-connections/tree/v2.0.0).
