### ISSUE TITLE
port_forwarding.sh getSignature compatibility with *.privacy.network hostname

### ISSUE THREAD

**Issue by ddelange** [pia-foss/manual-connections#85]
Hello,

My DD-WRT router runs OpenVPN over [de-frankfurt.privacy.network](de-frankfurt.privacy.network), which serves a VLAN running dhcpd on `192.168.22.*` and NextGen DNS.

I'm now attempting to open a port (either from the router via `telnet` or from my local machine in the VLAN), which I can then add to my router's port forwarding table.

As the router does not use the rest of the scripts in this repo but rather the builtin ovpn client to manage connection, I'm trying to get a port forwarded exclusively using `get_token.sh` and `port_forwarding.sh` on [de-frankfurt.privacy.network](de-frankfurt.privacy.network). 

If from my local machine I attempt to use the (different) host and gateway returned by `get_region.py`, naturally `port_forwarding.sh` errors with:
```console
$ PF_GATEWAY=$serverIP PF_HOSTNAME=$serverHostname PIA_TOKEN=$PIA_TOKEN ./port_forwarding.sh
...
Getting new signature... The payload_and_signature variable does not contain an OK status.
{
    "status": "ERROR",
    "message": "Unauthorized client"
}
```

Manual attempts at [de-frankfurt.privacy.network](de-frankfurt.privacy.network) from my local machine with either the `ca.rsa.4096.crt` from this repo, or the cacert from [`de-frankfurt.ovpn`](https://www.privateinternetaccess.com/openvpn/openvpn.zip) hint at a bad certificate:

```console
$ curl -m 5 --resolve -G --cacert "ca.rsa.4096.crt" "https://de-frankfurt.privacy.network:19999/getSignature?token=iy3***Vs="
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

# nothing but timeouts here
$ ip route list | grep via
default via 192.168.22.1 dev en0
3.89.223.191/32 via 192.168.22.1 dev en0
127.0.0.0/8 via 127.0.0.1 dev lo0
127.0.0.1/32 via 127.0.0.1 dev lo0

# let's try this IP as gateway
$ ping -c1 de-frankfurt.privacy.network | grep PING
PING de-frankfurt.privacy.network (138.199.18.172): 56 data bytes

# without --resolve, adapting --connect-to from port_forwarding.sh
$ curl -m 5 --connect-to "de-frankfurt.privacy.network::138.199.18.172:" --cacert "ca.rsa.4096.crt" -G "https://de-frankfurt.privacy.network:19999/getSignature?token=iy3***Vs="
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

# without --cacert
$ curl -m 5 --connect-to "de-frankfurt.privacy.network::138.199.18.172:" -G "https://de-frankfurt.privacy.network:19999/getSignature?token=iy3***Vs="
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

`port_forwarding.sh` is less verbose by default but the same response can be produced:
```console
$ PF_GATEWAY=138.199.18.172 PF_HOSTNAME=de-frankfurt.privacy.network PIA_TOKEN=$PIA_TOKEN ./port_forwarding.sh
...
Getting new signature... The payload_and_signature variable does not contain an OK status.
```

Any help towards a successful `getSignature` would be greatly appreciated!

**Comment by ddelange** [comment]
Maybe I'm using the wrong gateway IP (from `ping`), causing the certificate check to fail?

How can I verify this? Below is what I need I guess, but the VPN client is booted on router startup ~so no way to retrieve it after the fact I guess~?

https://github.com/pia-foss/manual-connections/blob/742a492eee5ecf947ea9cb7a5f887c3512d60dba/openvpn_config/openvpn_up.sh#L1-L4

After some further digging: the router actually stores `$route_vpn_gateway` in a file: https://github.com/mirror/dd-wrt/blob/2c7b55a/src/router/services/services/openvpn.c#L100-L105

`telnet` into the router:
```console
$ cat /tmp/gateway.txt

10.42.112.1
10.42.112.83

10.27.112.1
10.27.112.123
```

Tried them all, resulting in a mix of curl errors:

```
curl: (28) Connection timed out after 5000 milliseconds

curl: (60) SSL certificate problem: unable to get local issuer certificate

curl: (7) Failed to connect to 10.27.112.123 port 19999: Connection refused
```

**Comment by g00nix** [comment]
You hit the nail on the head. The PF API on that server didn't get restarted on that server after the Let's Encrypt certificate got renewed. This might affect servers running older builds. We already have a new build with improved separation of the PF API, which allows us more control over the API, so this shouldn't happen at all after all the servers get updated (this might take a while).

I think nobody reported this before because people always used the self signed when connecting to the PF API. You also tried to use the self signed, however you specified the CA to curl, not to the PF API. When you connect using `de-frankfurt.privacy.network`, curl also sends that in the SNI field of the SSL/TLS package, which causes the PF API to return the Let's Encrypt certificate instead of the self-signed.

Thank you for the bug report on the expired Let's Encrypt certificate, though.

I suggest running curl with `-k` for now, as the connections are behind firewall and already encrypted via VPN. If you wanna use a cert, you can check the CN that you get when using the self-signed certificate and specifying that in curl, like this:
```bash
root@d899058fbfd0:/# # do the first curl to trigger an error so that you can see the CN in the cert
root@d899058fbfd0:/# curl -v --cacert "/ca.rsa.4096.crt" -m 5 "https://138.199.18.136:19999/getSignature"
*   Trying 138.199.18.136...
* TCP_NODELAY set
* Connected to 138.199.18.136 (138.199.18.136) port 19999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /ca.rsa.4096.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=frankfurt407; name=frankfurt407
*  start date: Nov 11 08:01:48 2020 GMT
*  expire date: May 10 08:01:48 2021 GMT
*  subjectAltName does not match 138.199.18.136
* SSL: no alternative certificate subject name matches target host name '138.199.18.136'
* stopped the pause stream!
* Closing connection 0
* TLSv1.3 (OUT), TLS Unknown, Unknown (21):
* TLSv1.3 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name '138.199.18.136'



root@d899058fbfd0:/# # specify the CN to curl
root@d899058fbfd0:/# curl -v --cacert "/ca.rsa.4096.crt" -m 5 --connect-to "frankfurt407::138.199.18.136" "https://frankfurt407:19999/getSignature"
* Connecting to hostname: 138.199.18.136
*   Trying 138.199.18.136...
* TCP_NODELAY set
* Connected to 138.199.18.136 (138.199.18.136) port 19999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /ca.rsa.4096.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=frankfurt407; name=frankfurt407
*  start date: Nov 11 08:01:48 2020 GMT
*  expire date: May 10 08:01:48 2021 GMT
*  subjectAltName: host "frankfurt407" matched cert's "frankfurt407"
*  issuer: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=Private Internet Access; name=Private Internet Access; emailAddress=secure@privateinternetaccess.com
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x56060cf29580)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET /getSignature HTTP/2
> Host: frankfurt407:19999
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 401 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 64
< date: Sun, 24 Jan 2021 15:33:02 GMT
< 
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{
    "status": "ERROR",
    "message": "Unauthorized client"
}
* Connection #0 to host 138.199.18.136 left intact
root@d899058fbfd0:/# 
```

Since you connect using the DNS entry, you will not know the CN of the server you connected to, that is why this trick is required. All servers get upgraded every few months so when you hit a new one, you won't get `certificate has expired` when using the FQDN on PF.

If you want to follow the recommended procedure of getting the server's CN, please have a look at [get_region.sh](https://github.com/pia-foss/manual-connections/blob/master/get_region.sh).

**Comment by ddelange** [comment]
Hi @g00nix, thanks for the quick response!

> You also tried to use the self signed, however you specified the CA to curl, not to the PF API.

I'm not sure I understood completely, but will keep an eye out and retry with CA in the future.

For now, with `-k`, I do get a response but still no luck getting a signature :( Do you have any additional pointers?

```console
$ curl -v -k -m 5 --connect-to "frankfurt407::138.199.18.136" "https://frankfurt407:19999/getSignature?token=***"
* Connecting to hostname: 138.199.18.136
*   Trying 138.199.18.136...
* TCP_NODELAY set
* Connected to 138.199.18.136 (138.199.18.136) port 19999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=frankfurt407; name=frankfurt407
*  start date: Nov 11 08:01:48 2020 GMT
*  expire date: May 10 08:01:48 2021 GMT
*  issuer: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=Private Internet Access; name=Private Internet Access; emailAddress=secure@privateinternetaccess.com
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8e6780d600)
> GET /getSignature?token=*** HTTP/2
> Host: frankfurt407:19999
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 401
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 64
< date: Sun, 24 Jan 2021 16:08:46 GMT
<
{
    "status": "ERROR",
    "message": "Unauthorized client"
}
* Connection #0 to host 138.199.18.136 left intact
* Closing connection 0
```

**Comment by g00nix** [comment]
> > You also tried to use the self signed, however you specified the CA to curl, not to the PF API.

> I'm not sure I understood completely, but will keep an eye out and retry with CA in the future.

When using curl, you can inform curl of the CA certificate against which it should verify the signature of the certificate returned by the server. Curl will also verify that the certificate returned by the server and signed by the CA also contains the correct CN or SAN (these two are different things; more details can be found [here](https://tools.ietf.org/html/rfc6125)).  At the same time, curl will send the expected CN to the HTTPS server in the SNI field of the SSL/TLS package.

You were giving curl (client) the self-signed CA, but informing the PF API (the server) that you are expecting a certificate that contains the FQDN (signed by Let's Encrypt, not by the self signed CA).

> I do get a response but still no luck getting a signature :( Do you have any additional pointers?

It looks like you are not encoding the URL. Please follow the instructions in [port_forwarding.sh](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh).

> Is there a 'newer' server than de-frankfurt I can try out? Where to start with auth debugging?

You can try `berlin416` on IP `154.13.1.13`.

**Comment by StudioEtrange** [comment]
Not sure but I have the same problem of `unable to get local issuer certificate`
I use get_token.sh, and port_forwarding.sh, will all env var setted
and same problem occurs when getting new signature in port_fowarding.sh

* i use the ovpn files you provided here : https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files

```

curl -v -m 5     --connect-to "$PF_HOSTNAME::$PF_GATEWAY:"     --cacert "/whatever/manual-connections/ca.rsa.4096.crt"     -G --data-urlencode "token=${PIA_TOKEN}"     "https://${PF_HOSTNAME}:19999/getSignature"
* Connecting to hostname: 10.13.112.1
*   Trying 10.13.112.1:19999...
* Connected to 10.13.112.1 (10.13.112.1) port 19999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /whatever/manual-connections/ca.rsa.4096.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Real values are : 
```curl -v -m 5 --connect-to de-berlin.privacy.network::10.13.112.1: --cacert /whatever/manual-connections/ca.rsa.4096.crt -G --data-urlencode token=***** https://de-berlin.privacy.network:19999/getSignature```

I have also tried with server from switzerland

**Comment by ddelange** [comment]
Can confirm that also `de_berlin` is returning `Unauthorized client` when ignoring certificate (`curl -k`), just like `de-frankfurt`. This time I also tried with the Mac PIA client running the connection to berlin, instead of changing settings in my router.

```console
$ sudo -E bash get_region.sh

Getting the server list...OK!

Checking login credentials...OK!

date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
PIA_TOKEN=A***Io=

This token will expire in 24 hours, on .


Getting new signature... * Connecting to hostname: 154.13.1.150
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 154.13.1.150...
* TCP_NODELAY set
* Connected to 154.13.1.150 (154.13.1.150) port 19999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [223 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [64 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1968 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [556 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=berlin425; name=berlin425
*  start date: Nov  5 15:17:38 2020 GMT
*  expire date: May  4 15:17:38 2021 GMT
*  issuer: C=US; ST=CA; L=LosAngeles; O=Private Internet Access; OU=Private Internet Access; CN=Private Internet Access; name=Private Internet Access; emailAddress=secure@privateinternetaccess.com
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fbff380f600)
> GET /getSignature?token=A***Io%3D HTTP/2
> Host: berlin425:19999
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 401
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 64
< date: Sat, 30 Jan 2021 09:44:13 GMT
<
{ [64 bytes data]
100    64  100    64    0     0    336      0 --:--:-- --:--:-- --:--:--   336
* Connection #0 to host 154.13.1.150 left intact
* Closing connection 0
The payload_and_signature variable does not contain an OK status.
Response:
{
    "status": "ERROR",
    "message": "Unauthorized client"
}
```

**Comment by ddelange** [comment]
edit: spotted discrepancies between the IP you posted @g00nix, the IP that `get_region.py` returns, and the IP the PIA Mac client connects to. All berlin, but all different IPs. Probably the same problem with the router. Will try to sync them up and report back. Worst case would be using a static IP `ovpn` profile...

**Comment by ddelange** [comment]
What can be the root causes of `Unauthorized client` @g00nix?

To understand the situation better: when running port_forwarding.sh, does it need to get passed the same IP as the GUI/router is connected to? Or is the PF API running on a different IP and there is no correlation between them? For now, `ovpnudp` and the region is the only common factor between the shell scripts and PIA Mac client or the ovpn client on the router.

`get_region.py` gives `154.13.1.144`, a different IP than the Mac PIA client connects to (different each time of course).
```json
{"id": "de_berlin", "name": "DE Berlin", "country": "DE", "auto_region": true, "dns": "de-berlin.privacy.network", "port_forward": true, "geo": false, "servers": {"ovpnudp": [{"ip": "154.13.1.144", "cn": "berlin425"}], "ovpntcp": [{"ip": "154.13.1.150", "cn": "berlin425"}], "ikev2": [{"ip": "154.13.1.141", "cn": "berlin425"}], "wg": [{"ip": "154.13.1.139", "cn": "berlin425"}], "meta": [{"ip": "154.13.1.138", "cn": "berlin425"}]
```

Tried all combinations I could think of, without success. E.g. your suggested combo:

berlin416, 154.13.1.13: 
```
{
    "status": "ERROR",
    "message": "Unauthorized client"
}
```

Or the IP which the PIA Mac client is connected to, with different CNs, or the IP that `get_region.py` gives, no success... Either a `Unauthorized client` or a `Connection refused`:
```
curl: (7) Failed to connect to 154.13.1.53 port 19999: Connection refused
```

**Comment by ddelange** [comment]
Ah, I just saw #35. Can you confirm that is my issue?

**Comment by g00nix** [comment]
@ddelange 

> What can be the root causes of `Unauthorized client` @g00nix?

The network `10.0.0.0/8` is reserved on the node for VPN services and nobody can get an address on that network unless they have an active VPN connection. This makes sure that the PF API can not be access by anybody that is not already connected.

Make sure you access the Port Forwarding API by using your private IP address, not the public one. I think you are getting this error because you are connecting to the PF API using the public IP, which is going outside of the tunnel, instead of sending the request through the tunnel with your virtual IP address, the one in the network `10.0.0.0/8` (the exact address and subnet depends on the protocol and the random IP assignation algorithm  running for each protocol). 

You will probably have to get the IP of the gateway after connecting (as the scripts in this repo do), so that you query the PF API by using the private IP, not the public one.

---

@StudioEtrange you are sending the SNI of the FQDN, bound to the Let's Encrypt certificate, but you are requesting the certificate sent by the API to be signed by the self-signed PIA CA. I explained this in [this comment](https://github.com/pia-foss/manual-connections/issues/85#issuecomment-766391093).

**Comment by TheWug** [comment]
I wish curl (or any other tool for that matter, it seems none do, not even `openssl s_connect`) had an option to ignore one specific TLS error (e.g., certificate expired). Disabling all certificate validation is an unfortunate workaround.

**Comment by g00nix** [comment]
> I wish curl (or any other tool for that matter, it seems none do, not even `openssl s_connect`) had an option to ignore one specific TLS error (e.g., certificate expired). Disabling all certificate validation is an unfortunate workaround.

You are right. To avoid this unfortunate scenario, please read the [port forwarding script](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh) and please read the comments in the duplicate tickets. All required details have been provided within the script and the tickets to help the user establish a secure SSL/TLS connection.
