### ISSUE TITLE
Do not check if current user is root

### ISSUE THREAD

**Issue by StudioEtrange** [pia-foss/manual-connections#89]
In get_token.sh, get_region.sh and run_setup.sh, there is hardcoded check that stop scripts if the current user is not root.

```
if [ "$(whoami)" != "root" ]; then
  echo -e "${RED}This script needs to be run as root. Try again with 'sudo $0'${NC}"
  exit 1
fi
```

This is annoying in the situation where 
* when I run openvpn client into docker with a specific user which is not root ! And I do not want to be root nor install sudo inside the image (that i do not own)
* OR my current user have enough right to create folder /opt/ovpn-manual 
* OR if I have already tweak my user for automation and security purpose (but a non root  user)

Could we just remove these 3 checks that stop execution !

**Comment by g00nix** [comment]
Removing these lines of code will break functionality for most users, and the goal of the project is to make the VPN service accessible to all people that are having troubles running the software. This means that the master branch must run smooth for common configurations.

I appreciate the fact that you have advanced automation and Linux skill, so please fork the project, or just remove the lines of code before execution.
