### ISSUE TITLE
adapter_check variable /sbin/ip output needs a redirect

### ISSUE THREAD

**Issue by ToniCipriani** [pia-foss/manual-connections#97]
https://github.com/pia-foss/manual-connections/blob/366f132d1e377e81405787f5fab6d7458966cf2f/connect_to_openvpn_with_token.sh#L40

This doesn't appear to work on some OSes, I had to add a `2>&1` at the end of the command for it to work, otherwise the output is not assigned to the variable.

Tried on Raspian Buster.

The line became: 
`adapter_check="$( ip a s tun06 2>&1 )"`

**Comment by ToniCipriani** [comment]
Looks like this is already on Master, I was looking at v1.0.0.

**Comment by g00nix** [comment]
Looks like less work for me. 😄
